/*
 * Cdb_protocol.h,v 1.16 2000/05/31 08:54:49 jdurand Exp
 */

#ifndef __Cdb_protocol_h
#define __Cdb_protocol_h

/* Cdb version : 100 * real version */
#ifdef CDB_VERSION
#undef CDB_VERSION
#endif
#define CDB_VERSION 100

#ifdef CDB_PROTOCOL_LOGIN
#undef CDB_PROTOCOL_LOGIN
#endif
#define CDB_PROTOCOL_LOGIN 0

#ifdef CDB_PROTOCOL_LOGOUT
#undef CDB_PROTOCOL_LOGOUT
#endif
#define CDB_PROTOCOL_LOGOUT 1

#ifdef CDB_PROTOCOL_LOGIN_ADD_USER
#undef CDB_PROTOCOL_LOGIN_ADD_USER
#endif
#define CDB_PROTOCOL_LOGIN_ADD_USER 2

#ifdef CDB_PROTOCOL_LOGIN_REMOVE_USER
#undef CDB_PROTOCOL_LOGIN_REMOVE_USER
#endif
#define CDB_PROTOCOL_LOGIN_REMOVE_USER 3

#ifdef CDB_PROTOCOL_LOGIN_ADD_DB
#undef CDB_PROTOCOL_LOGIN_ADD_DB
#endif
#define CDB_PROTOCOL_LOGIN_ADD_DB 4

#ifdef CDB_PROTOCOL_LOGIN_REMOVE_DB
#undef CDB_PROTOCOL_LOGIN_REMOVE_DB
#endif
#define CDB_PROTOCOL_LOGIN_REMOVE_DB 5

#ifdef CDB_PROTOCOL_DB_ADD
#undef CDB_PROTOCOL_DB_ADD
#endif
#define CDB_PROTOCOL_DB_ADD 6

#ifdef CDB_PROTOCOL_DB_REMOVE
#undef CDB_PROTOCOL_DB_REMOVE
#endif
#define CDB_PROTOCOL_DB_REMOVE 7

#ifdef CDB_PROTOCOL_OPEN
#undef CDB_PROTOCOL_OPEN
#endif
#define CDB_PROTOCOL_OPEN 8

#ifdef CDB_PROTOCOL_CLOSE
#undef CDB_PROTOCOL_CLOSE
#endif
#define CDB_PROTOCOL_CLOSE 9

#ifdef CDB_PROTOCOL_FETCH
#undef CDB_PROTOCOL_FETCH
#endif
#define CDB_PROTOCOL_FETCH 10

#ifdef CDB_PROTOCOL_INSERT
#undef CDB_PROTOCOL_INSERT
#endif
#define CDB_PROTOCOL_INSERT 11

#ifdef CDB_PROTOCOL_UPDATE
#undef CDB_PROTOCOL_UPDATE
#endif
#define CDB_PROTOCOL_UPDATE 12

#ifdef CDB_PROTOCOL_PKEYFIND
#undef CDB_PROTOCOL_PKEYFIND
#endif
#define CDB_PROTOCOL_PKEYFIND 13

#ifdef CDB_PROTOCOL_PKEYNEXT
#undef CDB_PROTOCOL_PKEYNEXT
#endif
#define CDB_PROTOCOL_PKEYNEXT 14

#ifdef CDB_PROTOCOL_PKEYPREV
#undef CDB_PROTOCOL_PKEYPREV
#endif
#define CDB_PROTOCOL_PKEYPREV 15

#ifdef CDB_PROTOCOL_KEYFIND
#undef CDB_PROTOCOL_KEYFIND
#endif
#define CDB_PROTOCOL_KEYFIND 16

#ifdef CDB_PROTOCOL_KEYNEXT
#undef CDB_PROTOCOL_KEYNEXT
#endif
#define CDB_PROTOCOL_KEYNEXT 17

#ifdef CDB_PROTOCOL_KEYPREV
#undef CDB_PROTOCOL_KEYPREV
#endif
#define CDB_PROTOCOL_KEYPREV 18

#ifdef CDB_PROTOCOL_UNLOCK
#undef CDB_PROTOCOL_UNLOCK
#endif
#define CDB_PROTOCOL_UNLOCK 19

#ifdef CDB_PROTOCOL_DELETE
#undef CDB_PROTOCOL_DELETE
#endif
#define CDB_PROTOCOL_DELETE 20

#ifdef CDB_PROTOCOL_UNIQUEID
#undef CDB_PROTOCOL_UNNIQUEID
#endif
#define CDB_PROTOCOL_UNIQUEID 21

#ifdef CDB_PROTOCOL_SHUTDOWN
#undef CDB_PROTOCOL_SHUTDOWN
#endif
#define CDB_PROTOCOL_SHUTDOWN 22

#ifdef CDB_PROTOCOL_UNLOCK_ALL
#undef CDB_PROTOCOL_UNLOCK_ALL
#endif
#define CDB_PROTOCOL_UNLOCK_ALL 23

#ifdef CDB_PROTOCOL_DUMP_START
#undef CDB_PROTOCOL_DUMP_START
#endif
#define CDB_PROTOCOL_DUMP_START 24

#ifdef CDB_PROTOCOL_DUMP
#undef CDB_PROTOCOL_DUMP
#endif
#define CDB_PROTOCOL_DUMP 25

#ifdef CDB_PROTOCOL_DUMP_END
#undef CDB_PROTOCOL_DUMP_END
#endif
#define CDB_PROTOCOL_DUMP_END 26

#ifdef CDB_PROTOCOL_PING
#undef CDB_PROTOCOL_PING
#endif
#define CDB_PROTOCOL_PING 27

#ifdef CDB_PROTOCOL_PWDFILE_DUMP_START
#undef CDB_PROTOCOL_PWDFILE_DUMP_START
#endif
#define CDB_PROTOCOL_PWDFILE_DUMP_START 28

#ifdef CDB_PROTOCOL_XXXFILE_DUMP_SIZE
#undef CDB_PROTOCOL_XXXFILE_DUMP_SIZE
#endif
#define CDB_PROTOCOL_XXXFILE_DUMP_SIZE 29

#ifdef CDB_PROTOCOL_XXXFILE_DUMP
#undef CDB_PROTOCOL_XXXFILE_DUMP
#endif
#define CDB_PROTOCOL_XXXFILE_DUMP 30

#ifdef CDB_PROTOCOL_XXXFILE_DUMP_END
#undef CDB_PROTOCOL_XXXFILE_DUMP_END
#endif
#define CDB_PROTOCOL_XXXFILE_DUMP_END 31

#ifdef CDB_PROTOCOL_DEBUG
#undef CDB_PROTOCOL_DEBUG
#endif
#define CDB_PROTOCOL_DEBUG 32

#ifdef CDB_PROTOCOL_FIRSTROW
#undef CDB_PROTOCOL_FIRSTROW
#endif
#define CDB_PROTOCOL_FIRSTROW 33

#ifdef CDB_PROTOCOL_NEXTROW
#undef CDB_PROTOCOL_NEXTROW
#endif
#define CDB_PROTOCOL_NEXTROW 34

#ifdef CDB_PROTOCOL_INIT
#undef CDB_PROTOCOL_INIT
#endif
#define CDB_PROTOCOL_INIT 35

#ifdef CDB_PROTOCOL_DESFILE_DUMP_START
#undef CDB_PROTOCOL_DESFILE_DUMP_START
#endif
#define CDB_PROTOCOL_DESFILE_DUMP_START 36

#endif /* __Cdb_protocol_h */

/*
 * Last Update: "Wednesday 31 May, 2000 at 09:58:21 CEST by Jean-Damien Durand (<A HREF='mailto:Jean-Damien.Durand@cern.ch'>Jean-Damien.Durand@cern.ch</A>)"
 */
